name: Lighthouse CI Action
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Lighthouse CI Action
      uses: treosh/lighthouse-ci-action@v3
      with:
        # Number of runs to do per URL
        runs: 3
        # API token to push to LHCI server
        serverToken: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
